package com.t5.enterpriseprocurement.dto;

import java.time.LocalDate;

import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotNull;

public class GeneratePurchaseOrderDTO {

    @NotNull(message = "Generated by user ID is required")
    private Integer generatedByUserId;

    @NotNull(message = "Expected delivery date is required")
    @FutureOrPresent(
            message = "Expected delivery date cannot be in the past"
    )
    private LocalDate expectedDeliveryDate;

    public Integer getGeneratedByUserId() {
        return generatedByUserId;
    }

    public void setGeneratedByUserId(Integer generatedByUserId) {
        this.generatedByUserId = generatedByUserId;
    }

    public LocalDate getExpectedDeliveryDate() {
        return expectedDeliveryDate;
    }

    public void setExpectedDeliveryDate(
            LocalDate expectedDeliveryDate) {
        this.expectedDeliveryDate = expectedDeliveryDate;
    }
}