import { useEffect } from 'react'
import { Add, Close, Search } from '@mui/icons-material'
import { titleCase } from '../utils'
export const Button = ({ children, variant = 'primary', icon, className = '', ...props }) => <button className={`button ${variant} ${className}`} {...props}>{icon}{children}</button>
export const PageHeader = ({ title, description, action }) => <div className="page-header"><div><p className="eyebrow">Procurement workspace</p><h1>{title}</h1>{description && <p className="page-description">{description}</p>}</div>{action}</div>
export const StatusBadge = ({ status }) => <span className={`badge status-${String(status || '').toLowerCase().replaceAll('_', '-')}`}>{titleCase(status || 'Unknown')}</span>
export const RoleBadge = ({ role }) => <span className="badge role">{titleCase(role)}</span>
export const LoadingState = ({ text = 'Loading data…' }) => <div className="state"><span className="spinner" />{text}</div>
export const EmptyState = ({ title = 'Nothing to show', description = 'Data will appear here when it is available.', action }) => <div className="state empty"><div className="empty-icon">◫</div><h3>{title}</h3><p>{description}</p>{action}</div>
export const ErrorState = ({ error, retry }) => <div className="state error"><h3>Unable to load this page</h3><p>{error}</p>{retry && <Button onClick={retry}>Try again</Button>}</div>
export function DataTable({ columns, rows, loading, error, retry, emptyTitle, emptyDescription }) { if (loading) return <LoadingState />; if (error) return <ErrorState error={error} retry={retry} />; if (!rows?.length) return <EmptyState title={emptyTitle} description={emptyDescription} />; return <div className="table-wrap"><table><thead><tr>{columns.map((c) => <th key={c.label}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={row.id || row.requestId || row.supplierId || row.deptId || row.categoryId || row.hierarchyId || i}>{columns.map((c) => <td key={c.label}>{c.render ? c.render(row) : row[c.key] ?? '—'}</td>)}</tr>)}</tbody></table></div> }
export const SearchBar = ({ value, onChange, placeholder = 'Search…' }) => <label className="search"><Search fontSize="small" /><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /></label>
export function Modal({ open, title, children, onClose }) { useEffect(() => { const listener = (e) => e.key === 'Escape' && onClose?.(); window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener) }, [onClose]); if (!open) return null; return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-title"><h2>{title}</h2><button className="icon-button" onClick={onClose}><Close /></button></div>{children}</section></div> }
export const AddButton = ({ children = 'Add', ...props }) => <Button icon={<Add fontSize="small" />} {...props}>{children}</Button>
