import axios from 'axios'
const client = axios.create({ headers: { 'Content-Type': 'application/json' } })
client.interceptors.request.use((config) => { const token = localStorage.getItem('procurement_token'); if (token) config.headers.Authorization = `Bearer ${token}`; return config })
client.interceptors.response.use((response) => response, (error) => { if (error.response?.status === 401) { localStorage.removeItem('procurement_auth'); localStorage.removeItem('procurement_token'); window.dispatchEvent(new Event('procurement:unauthorized')) } return Promise.reject(error) })
export default client
export const authApi = { login: (body) => client.post('/api/auth/login', body), register: (body) => client.post('/api/auth/register', body), forgotPassword: (body) => client.post('/api/auth/forgot-password', body), resetPassword: (body) => client.post('/api/auth/reset-password', body) }
export const dashboardApi = { summary: () => client.get('/dashboard/summary') }
export const requestApi = { list: () => client.get('/purchase-requests'), get: (id) => client.get(`/purchase-requests/${id}`), create: (body) => client.post('/purchase-requests', body), update: (id, body) => client.put(`/purchase-requests/${id}`, body), remove: (id) => client.delete(`/purchase-requests/${id}`), submit: (id) => client.put(`/purchase-requests/${id}/submit`), approve: (id, stage) => client.put(`/purchase-requests/${id}/${stage}-approve`), selectSupplier: (id, supplierId) => client.put(`/purchase-requests/${id}/select-supplier/${supplierId}`), items: (id) => client.get(`/purchase-requests/${id}/items`), addItem: (id, body) => client.post(`/purchase-requests/${id}/items`, body), updateItem: (id, itemId, body) => client.put(`/purchase-requests/${id}/items/${itemId}`, body), removeItem: (id, itemId) => client.delete(`/purchase-requests/${id}/items/${itemId}`) }
export const suppliersApi = crud('/suppliers'); export const complianceApi = crud('/supplier-compliance'); export const departmentsApi = crud('/departments'); export const categoriesApi = crud('/categories'); export const hierarchyApi = crud('/approval-hierarchy')
export const purchaseOrdersApi = { list: () => client.get('/purchase-orders'), get: (id) => client.get(`/purchase-orders/${id}`), generate: (id) => client.post(`/purchase-orders/generate/${id}`) }
export const reportsApi = { spend: () => client.get('/reports/spend'), suppliers: () => client.get('/reports/suppliers'), departments: () => client.get('/reports/departments'), monthly: () => client.get('/reports/monthly'), download: (kind) => client.get(`/reports/export/${kind}`, { responseType: 'blob' }) }
export const auditLogsApi = { list: () => client.get('/api/audit-logs') }
function crud(path) { return { list: () => client.get(path), get: (id) => client.get(`${path}/${id}`), create: (body) => client.post(path, body), update: (id, body) => client.put(`${path}/${id}`, body), remove: (id) => client.delete(`${path}/${id}`) } }
