import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { Check } from '@mui/icons-material'
import { requestApi } from '../api/client'
import { useAuth } from '../context/AuthContext'
import { Button,DataTable,PageHeader,SearchBar,StatusBadge } from '../components/UI'
import { date,message,money } from '../utils'
const statusFor={MANAGER:'PENDING_MANAGER_APPROVAL',FINANCE:'PENDING_FINANCE_APPROVAL',PROCUREMENT:'PENDING_PROCUREMENT_APPROVAL'}
export default function ApprovalsPage(){const {user}=useAuth(),[rows,setRows]=useState([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(null);const load=async()=>{setLoading(true);try{setRows((await requestApi.list()).data);setError('')}catch(e){setError(message(e))}finally{setLoading(false)}};useEffect(()=>{load()},[]);const pending=useMemo(()=>rows.filter(r=>r.status===statusFor[user.role]).filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q,user.role]);const approve=async(id)=>{setBusy(id);try{await requestApi.approve(id,user.role.toLowerCase());await load()}catch(e){setError(message(e))}finally{setBusy(null)}};return <><PageHeader title="Approval queue" description="Review and approve requests currently assigned to your role."/><div className="toolbar"><SearchBar value={q} onChange={setQ} placeholder="Search pending requests…"/>{error&&<span className="form-error inline">{error}</span>}</div><section className="panel"><DataTable loading={loading} error={error&&!rows.length?error:null} retry={load} rows={pending} emptyTitle="Your approval queue is clear" emptyDescription="There are no requests awaiting your approval." columns={[{label:'Request',render:r=><Link to={`/purchase-requests/${r.requestId}`}>{r.requestNumber}</Link>},{label:'Requester',key:'createdBy'},{label:'Department',key:'departmentName'},{label:'Amount',render:r=>money(r.estimatedAmount)},{label:'Date',render:r=>date(r.createdAt)},{label:'Status',render:r=><StatusBadge status={r.status}/>},{label:'Action',render:r=><div className="row-actions"><Link className="button secondary small" to={`/purchase-requests/${r.requestId}`}>View</Link><Button className="small" disabled={busy===r.requestId} icon={<Check fontSize="small"/>} onClick={()=>approve(r.requestId)}>{busy===r.requestId?'…':'Approve'}</Button></div>}]} /></section></>}
