import { useEffect, useState } from 'react'
import { complianceApi, suppliersApi } from '../api/client'
import { AddButton, Button, DataTable, Modal, PageHeader, SearchBar, StatusBadge } from '../components/UI'
import { date, message } from '../utils'

const blank = { supplier: { supplierId: '' }, gstVerified: false, panVerified: false, isoCertified: false, licenseExpiry: '', complianceStatus: 'PENDING' }
export default function CompliancePage() {
  const [rows, setRows] = useState([]); const [suppliers, setSuppliers] = useState([]); const [q, setQ] = useState(''); const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { const [c, s] = await Promise.all([complianceApi.list(), suppliersApi.list()]); setRows(c.data); setSuppliers(s.data); setError('') } catch (e) { setError(message(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const save = async e => { e.preventDefault(); try { if (form.complianceId) await complianceApi.update(form.complianceId, form); else await complianceApi.create(form); setOpen(false); setForm(blank); await load() } catch (e) { setError(message(e)) } }
  const remove = async row => { if (!confirm('Delete this compliance record?')) return; try { await complianceApi.remove(row.complianceId); await load() } catch (e) { setError(message(e)) } }
  const filtered = rows.filter(row => JSON.stringify(row).toLowerCase().includes(q.toLowerCase()))
  return <><PageHeader title="Supplier compliance" description="Track verification and licensing requirements." action={<AddButton onClick={() => { setForm(blank); setOpen(true) }}>Add compliance</AddButton>} /><div className="toolbar"><SearchBar value={q} onChange={setQ} />{error && <span className="form-error inline">{error}</span>}</div><section className="panel"><DataTable loading={loading} error={error && !rows.length ? error : null} retry={load} rows={filtered} emptyTitle="No compliance records" columns={[{ label: 'Supplier', render: row => row.supplier?.supplierName || '—' }, { label: 'GST', render: row => row.gstVerified ? 'Verified' : 'Pending' }, { label: 'PAN', render: row => row.panVerified ? 'Verified' : 'Pending' }, { label: 'ISO', render: row => row.isoCertified ? 'Certified' : 'Not certified' }, { label: 'License expiry', render: row => date(row.licenseExpiry) }, { label: 'Status', render: row => <StatusBadge status={row.complianceStatus} /> }, { label: 'Actions', render: row => <div className="row-actions"><Button className="small" variant="secondary" onClick={() => { setForm(row); setOpen(true) }}>Edit</Button><Button className="small" variant="danger" onClick={() => remove(row)}>Delete</Button></div> }]} /></section><Modal open={open} title={form.complianceId ? 'Edit compliance' : 'Add compliance'} onClose={() => setOpen(false)}><form className="form" onSubmit={save}><div className="form-grid"><label>Supplier<select required value={form.supplier?.supplierId || ''} onChange={e => setForm({ ...form, supplier: { supplierId: Number(e.target.value) } })}><option value="">Select supplier</option>{suppliers.map(s => <option key={s.supplierId} value={s.supplierId}>{s.supplierName}</option>)}</select></label><label>License expiry<input type="date" value={form.licenseExpiry || ''} onChange={e => setForm({ ...form, licenseExpiry: e.target.value })} /></label><label>Status<select value={form.complianceStatus || 'PENDING'} onChange={e => setForm({ ...form, complianceStatus: e.target.value })}><option>COMPLIANT</option><option>NON_COMPLIANT</option><option>PENDING</option></select></label><div className="check-list">{[['gstVerified', 'GST verified'], ['panVerified', 'PAN verified'], ['isoCertified', 'ISO certified']].map(([key, label]) => <label className="check" key={key}><input type="checkbox" checked={Boolean(form[key])} onChange={e => setForm({ ...form, [key]: e.target.checked })} />{label}</label>)}</div></div><div className="form-actions"><Button variant="secondary" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit">Save compliance</Button></div></form></Modal></>
}
