import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Lock } from '@mui/icons-material'
import { authApi, departmentsApi } from '../api/client'
import { Button, ErrorState, LoadingState } from '../components/UI'
import { message } from '../utils'

const initial = { name: '', email: '', phone: '', departmentId: '', password: '', confirmPassword: '' }
export default function RegistrationPage() {
  const navigate = useNavigate(); const [form, setForm] = useState(initial); const [departments, setDepartments] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const load = async () => { setLoading(true); try { setDepartments((await departmentsApi.list()).data); setError('') } catch (e) { setError(message(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const submit = async (e) => { e.preventDefault(); if (form.password.length < 6) return setError('Password must be at least 6 characters.'); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); setBusy(true); setError(''); try { await authApi.register({ name: form.name.trim(), email: form.email.trim(), phone: form.phone.trim(), departmentId: Number(form.departmentId), password: form.password }); setSuccess('Account created successfully. Redirecting to sign in…'); setTimeout(() => navigate('/login'), 1200) } catch (err) { setError(message(err)) } finally { setBusy(false) } }
  if (loading) return <div className="login"><section className="login-panel"><LoadingState text="Preparing registration…" /></section></div>
  if (error && !departments.length) return <div className="login"><section className="login-panel"><ErrorState error={error} retry={load} /></section></div>
  return <div className="login"><section className="login-brand"><div className="login-logo"><Lock /></div><p className="eyebrow">Enterprise procurement</p><h1>Start with a secure employee account.</h1><p>New accounts have employee access and can submit purchase requests into the approval workflow.</p></section><section className="login-panel"><form className="login-form" onSubmit={submit}><div className="login-form-logo"><Lock /></div><h2>Create your account</h2><p>Register as an employee to get started.</p>{error && <div className="form-error">{error}</div>}{success && <div className="notice success">{success}</div>}<label>Full name<input required autoComplete="name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Email<input required type="email" autoComplete="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Phone<input required type="tel" pattern="[0-9+() -]{7,20}" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label>Department<select required value={form.departmentId} onChange={e => setForm({ ...form, departmentId: e.target.value })}><option value="">Select department</option>{departments.map(d => <option key={d.deptId} value={d.deptId}>{d.deptName}</option>)}</select></label><label>Password<input required minLength="6" type="password" autoComplete="new-password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><label>Confirm password<input required minLength="6" type="password" autoComplete="new-password" value={form.confirmPassword} onChange={e => setForm({ ...form, confirmPassword: e.target.value })} /></label><Button type="submit" disabled={busy || Boolean(success)} className="login-submit">{busy ? 'Creating account…' : 'Create employee account'}</Button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></section></div>
}
