import { useEffect,useState } from 'react'
import { Download } from '@mui/icons-material'
import { reportsApi } from '../api/client'
import { Button,DataTable,ErrorState,LoadingState,PageHeader } from '../components/UI'
import { message,money } from '../utils'
const download=async(kind)=>{const res=await reportsApi.download(kind);const url=URL.createObjectURL(res.data);const a=document.createElement('a');a.href=url;a.download=`Procurement_Report.${kind==='pdf'?'pdf':'xlsx'}`;a.click();URL.revokeObjectURL(url)}
export default function ReportsPage(){const [data,setData]=useState(null),[error,setError]=useState('');const load=async()=>{try{const [spend,suppliers,departments,monthly]=await Promise.all([reportsApi.spend(),reportsApi.suppliers(),reportsApi.departments(),reportsApi.monthly()]);setData({spend:spend.data,suppliers:suppliers.data,departments:departments.data,monthly:monthly.data});setError('')}catch(e){setError(message(e))}};useEffect(()=>{load()},[]);if(error)return <ErrorState error={error} retry={load}/>;if(!data)return <LoadingState/>;return <><PageHeader title="Reports" description="Procurement spend and operational performance reporting." action={<div className="header-actions"><Button variant="secondary" icon={<Download fontSize="small"/>} onClick={()=>download('pdf')}>PDF</Button><Button icon={<Download fontSize="small"/>} onClick={()=>download('excel')}>Excel</Button></div>}/><div className="report-grid"><ReportCard title="Spend analysis" data={data.spend}/><section className="panel"><h2>Monthly activity</h2><DataTable rows={data.monthly} columns={keys(data.monthly)}/></section><section className="panel"><h2>Supplier performance</h2><DataTable rows={data.suppliers} columns={keys(data.suppliers)}/></section><section className="panel"><h2>Department report</h2><DataTable rows={data.departments} columns={keys(data.departments)}/></section></div></>}
function keys(rows){return Object.keys(rows?.[0]||{}).map(k=>({label:k.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase()),render:r=>typeof r[k]==='number'&&/amount|spend|cost/i.test(k)?money(r[k]):r[k]??'—'}))}
function ReportCard({title,data}){return <section className="panel report-summary"><h2>{title}</h2>{data&&typeof data==='object'?<dl className="details">{Object.entries(data).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd>{typeof v==='number'&&/amount|spend|cost/i.test(k)?money(v):String(v)}</dd></div>)}</dl>:<p>No spend data available.</p>}</section>}
