import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { Lock, Visibility, VisibilityOff } from '@mui/icons-material'
import { authApi } from '../api/client'
import { Button } from '../components/UI'
import { message } from '../utils'

export default function ResetPasswordPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [form, setForm] = useState({ password: '', confirm: '' }); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const submit = async e => { e.preventDefault(); if (form.password.length < 6) return setError('Password must be at least 6 characters.'); if (form.password !== form.confirm) return setError('Passwords do not match.'); if (!params.get('token')) return setError('Invalid or expired reset link.'); setBusy(true); setError(''); try { await authApi.resetPassword({ token: params.get('token'), password: form.password }); setSuccess('Password reset successfully.'); } catch (err) { setError(message(err)) } finally { setBusy(false) } }
  return <div className="login"><section className="login-brand"><div className="login-logo"><Lock /></div><p className="eyebrow">ProcureFlow security</p><h1>Create a new password.</h1><p>Your new password will replace the existing password after this one-time reset.</p></section><section className="login-panel"><form className="login-form auth-card" onSubmit={submit}><div className="login-form-logo"><Lock /></div><h2>Reset password</h2><p>Choose a new password with at least 6 characters.</p>{error && <div className="form-error">{error}</div>}{success && <div className="notice success">{success}</div>}<label>New password<span className="password-input"><input required minLength="6" type={show ? 'text' : 'password'} autoComplete="new-password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><button type="button" aria-label="Toggle password visibility" onClick={() => setShow(!show)}>{show ? <VisibilityOff /> : <Visibility />}</button></span></label><label>Confirm password<input required minLength="6" type={show ? 'text' : 'password'} autoComplete="new-password" value={form.confirm} onChange={e => setForm({ ...form, confirm: e.target.value })} /></label>{success ? <Button type="button" onClick={() => navigate('/login')}>Back to login</Button> : <Button type="submit" disabled={busy}>{busy ? 'Resetting…' : 'Reset password'}</Button>}<p className="auth-switch"><Link to="/login">Back to sign in</Link></p></form></section></div>
}
