import { useEffect,useState } from 'react'
import { useLocation,useNavigate } from 'react-router-dom'
import { Edit } from '@mui/icons-material'
import { suppliersApi } from '../api/client'
import { AddButton,Button,DataTable,Modal,PageHeader,SearchBar,StatusBadge } from '../components/UI'
import { message } from '../utils'
const blank={supplierCode:'',supplierName:'',contactPerson:'',email:'',phone:'',address:'',gstNumber:'',status:'ACTIVE'}
export default function SuppliersPage(){const loc=useLocation(),nav=useNavigate(),[rows,setRows]=useState([]),[q,setQ]=useState(''),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{setRows((await suppliersApi.list()).data);setError('')}catch(e){setError(message(e))}finally{setLoading(false)}};useEffect(()=>{load()},[]);useEffect(()=>{if(loc.pathname.endsWith('/new'))setOpen(true)},[loc]);const save=async(e)=>{e.preventDefault();try{if(form.supplierId)await suppliersApi.update(form.supplierId,form);else await suppliersApi.create(form);setOpen(false);setForm(blank);await load();nav('/suppliers')}catch(e){setError(message(e))}};const edit=(r)=>{setForm(r);setOpen(true)};const remove=async(r)=>{if(!confirm(`Delete ${r.supplierName}?`))return;try{await suppliersApi.remove(r.supplierId);await load()}catch(e){setError(message(e))}};const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));return <><PageHeader title="Suppliers" description="Maintain supplier contact and registration details." action={<AddButton onClick={()=>setOpen(true)}>New supplier</AddButton>}/><div className="toolbar"><SearchBar value={q} onChange={setQ} placeholder="Search suppliers…"/>{error&&<span className="form-error inline">{error}</span>}</div><section className="panel"><DataTable loading={loading} error={error&&!rows.length?error:null} retry={load} rows={filtered} emptyTitle="No suppliers found" columns={[{label:'Code',key:'supplierCode'},{label:'Supplier',render:r=><strong>{r.supplierName}</strong>},{label:'Contact',render:r=><span>{r.contactPerson}<br/><small>{r.email}</small></span>},{label:'Phone',key:'phone'},{label:'GST',key:'gstNumber'},{label:'Status',render:r=><StatusBadge status={r.status}/>},{label:'Actions',render:r=><div className="row-actions"><Button variant="secondary" className="small" icon={<Edit fontSize="small"/>} onClick={()=>edit(r)}>Edit</Button><Button variant="danger" className="small" onClick={()=>remove(r)}>Delete</Button></div>}]} /></section><Modal open={open} title={form.supplierId?'Edit supplier':'New supplier'} onClose={()=>{setOpen(false);setForm(blank)}}><SupplierForm form={form} setForm={setForm} onSubmit={save} onCancel={()=>setOpen(false)}/></Modal></>}
function SupplierForm({form,setForm,onSubmit,onCancel}){const field=(name,label,type='text')=><label>{label}<input required={['supplierCode','supplierName','email'].includes(name)} type={type} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>;return <form className="form" onSubmit={onSubmit}><div className="form-grid">{field('supplierCode','Supplier code')}{field('supplierName','Supplier name')}{field('contactPerson','Contact person')}{field('email','Email','email')}{field('phone','Phone')}{field('gstNumber','GST number')}<label className="full">Address<input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Status<select value={form.status||'ACTIVE'} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label></div><div className="form-actions"><Button variant="secondary" type="button" onClick={onCancel}>Cancel</Button><Button type="submit">Save supplier</Button></div></form>}
