import { Navigate, Route, Routes } from 'react-router-dom'
import { AuthProvider } from './context/AuthContext'
import ProtectedRoute from './components/ProtectedRoute'
import AppLayout from './components/AppLayout'
import LoginPage from './pages/LoginPage'
import RegistrationPage from './pages/RegistrationPage'
import DashboardPage from './pages/DashboardPage'
import PurchaseRequestsPage from './pages/PurchaseRequestsPage'
import RequestFormPage from './pages/RequestFormPage'
import RequestDetailPage from './pages/RequestDetailPage'
import ApprovalsPage from './pages/ApprovalsPage'
import SuppliersPage from './pages/SuppliersPage'
import CompliancePage from './pages/CompliancePage'
import MasterDataPage from './pages/MasterDataPage'
import PurchaseOrdersPage from './pages/PurchaseOrdersPage'
import ReportsPage from './pages/ReportsPage'
import AuditLogsPage from './pages/AuditLogsPage'
import ForgotPasswordPage from './pages/ForgotPasswordPage'
import ResetPasswordPage from './pages/ResetPasswordPage'
const shell = (element, roles) => <ProtectedRoute roles={roles}><AppLayout>{element}</AppLayout></ProtectedRoute>
export default function App() { return <AuthProvider><Routes><Route path="/login" element={<LoginPage />} /><Route path="/register" element={<RegistrationPage />} /><Route path="/forgot-password" element={<ForgotPasswordPage />} /><Route path="/reset-password" element={<ResetPasswordPage />} /><Route path="/" element={shell(<DashboardPage />)} /><Route path="/dashboard" element={<Navigate to="/" replace />} /><Route path="/purchase-requests" element={shell(<PurchaseRequestsPage />)} /><Route path="/purchase-requests/new" element={shell(<RequestFormPage />)} /><Route path="/purchase-requests/:id" element={shell(<RequestDetailPage />)} /><Route path="/purchase-requests/:id/edit" element={shell(<RequestFormPage />)} /><Route path="/approvals" element={shell(<ApprovalsPage />, ['MANAGER','FINANCE','PROCUREMENT'])} /><Route path="/suppliers/*" element={shell(<SuppliersPage />, ['PROCUREMENT','ADMIN'])} /><Route path="/supplier-compliance" element={shell(<CompliancePage />, ['PROCUREMENT','ADMIN'])} /><Route path="/purchase-orders" element={shell(<PurchaseOrdersPage />, ['PROCUREMENT'])} /><Route path="/departments" element={shell(<MasterDataPage type="departments" />, ['ADMIN'])} /><Route path="/categories" element={shell(<MasterDataPage type="categories" />, ['ADMIN'])} /><Route path="/approval-hierarchy" element={shell(<MasterDataPage type="approval-hierarchy" />, ['ADMIN'])} /><Route path="/reports" element={shell(<ReportsPage />, ['ADMIN'])} /><Route path="/audit-logs" element={shell(<AuditLogsPage />, ['ADMIN'])} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></AuthProvider> }
